name: Setup Flyway

description: Downloads and installs flyway at the specified version

inputs:
  version:
    description: The version of flyway to install
    required: true
  architecture:
    description: 'Target operating system architecture for Flyway to use. Examples: x86, x64. Will use system architecture by default.'
    required: false
  use-redgate-url:
    description: 'Use the flyway tarball from the Redgate URL. If false, will pull from maven url. Default is false.'
    required: false
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'
