name: Test
on:
  # This workflow uses the pull_request trigger which prevents write permissions and secrets
  # access to the target repository from public forks.  This should remain as a pull_request
  # trigger because checkout, build, format and checking for changes do not need elevated
  # permissions to the repository.  The reduced permissions for public forks is adequate.
  pull_request:
    # Don't include any specific paths here so we always get a build that produces a status
    # check that our Branch Protection Rules can use.  Having a status check also allows us
    # to require that branches be up to date before they are merged.

concurrency:
  group: test-flyway-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test-flyway-version-514:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyway
        uses: ./
        with:
          version: 5.1.4

      - name: Check Version
        id: flyway-version
        shell: pwsh
        run: |
          $FlywayVersion = flyway -v
          if(-Not ($FlywayVersion -Match "5.1.4")) {
            exit code 1
          }

  test-flyway-version-700:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyway
        uses: ./
        with:
          version: 7.0.0

      - name: Check Version
        id: flyway-version
        shell: pwsh
        run: |
          $FlywayVersion = flyway -v
          if(-Not ($FlywayVersion -Match "7.0.0")) {
            exit code 1
          }

  test-flyway-version-10181-redgate:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flyway
        uses: ./
        with:
          version: 10.18.1
          use-redgate-url: true

      - name: Check Version
        id: flyway-version
        shell: pwsh
        run: |
          $FlywayVersion = flyway -v
          if(-Not ($FlywayVersion -Match "10.18.1")) {
            exit code 1
          }