name: Build
on: 
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  test-flyway-version-5.1.4:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flyway
        uses: ./
        with:
          version: 5.1.4
      - name: Check Version
        id: flyway-version
        shell: pwsh
        run: |
          $FlywayVersion = flyway -v
          if(-Not ($FlywayVersion -Match "5.1.4")) {
            exit code 1
          }